#!/bin/bash
# BEGIN_ICS_COPYRIGHT8 ****************************************
#
# Copyright (c) 2015-2023, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# END_ICS_COPYRIGHT8   ****************************************

# [ICS VERSION STRING: unknown]

# SLURM directives.  Must precede all non-comment lines and can't use variables
# slurm command line overrides any SBATCH settings here
# to disable a given setting below, use ## to comment out
##SBATCH --job-name=run_imb
#SBATCH --output=logs/IMB.%j.out
# timelimit in days-hours:minutes:seconds
##SBATCH --time=0-00:30:00

# BASE PATH TO MPI EXECUTABLES: To use an alternate location,
# either edit this line or set MPICH_PREFIX in your environment.
# see select_mpi for the set of default MPI selections
# default to MPI used for build
MPICH_PREFIX=${MPICH_PREFIX:-`cat .prefix 2>/dev/null`}

trap "exit 1" SIGHUP SIGTERM SIGINT

BASE_DIR="imb/"

if [ -z "$1" -o x"$1" == x"-h" -o x"$1" == x"--help" ]
then 
	echo "Usage: $0 number_of_processes [suite] [options]"
	echo "          or"
	echo "       $0 --help"
	echo "    number_of_processes may be 'all' in which case PROCS_PER_NODE ranks will"
	echo "                     be started for every entry in the MPI_HOSTS file"
	echo "    [suite] is the benchmark suite to run (default MPI1)"
	echo "    [options] are passed to the suite"
	echo
	echo -n "Possible suites are: "
	sep=""
	for f in ${BASE_DIR}IMB-*; do
		[ ! -x "$f" ] && continue;
		echo -n $sep$(basename $f|sed -e 's/IMB-//')
		sep=", "
	done
	echo
	echo
	echo "For example: $0 2"
	echo "For example: $0 16 allreduce barrier"
	echo "For example: $0 2 P2P pingpong"
	echo
	echo "For a list of the available IMB benchmarks please see the Intel"
	echo "MPI Benchmarks documentation."
	echo
	echo "To get more details about [options] available: $0 1 [suite] --help"
	echo "To get more details about an option: $0 1 [suite] --help option"
	exit 1
fi

NUM_PROCESSES=$1
shift
if [ -x "$BASE_DIR/IMB-$1" ]
then
	APP="IMB-$1"
	shift
else
	APP=IMB-MPI1
fi
if [ x"$1" = x"--help" -o x"$1" = x"-help" ]
then
	if [ x"$2" != x ]
	then
		set -- "-help" "$2"
	else
		set -- "-help"
	fi
	MIN_PROCESSES=1
fi

IMB_CMD="$BASE_DIR$APP"
LOGFILE=
. ./prepare_run

# to run a reduced suite of tests, uncomment a different one of these lines
# or specify test name on the command line
# full list of tests
CMD="$IMB_CMD"
#CMD="$IMB_CMD Bcast Barrier AllReduce Reduce exchange reduce_scatter pingping pingpong sendrecv alltoall allgather allgatherv"
# avoid allgather and alltoall, too much memory needed
#CMD="$IMB_CMD Bcast Barrier AllReduce Reduce exchange reduce_scatter pingping pingpong sendrecv"
#CMD="$IMB_CMD Bcast Barrier AllReduce Reduce"
#CMD="$IMB_CMD Bcast Barrier"
#CMD="$IMB_CMD Barrier"

(
	echo " Running Intel MPI Benchmark suite ..."
	show_mpi_hosts
	show_mpi_env
	set -x
	$MPI_RUN_CMD $CMD "$@"
	set +x
) 2>&1 | tee -i -a $LOGFILE
echo "########################################### " >> $LOGFILE
