#!/bin/bash
# BEGIN_ICS_COPYRIGHT8 ****************************************
#
# Copyright (c) 2015-2020, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# END_ICS_COPYRIGHT8   ****************************************

# [ICS VERSION STRING: unknown]

# BASE PATH TO MPI EXECUTABLES: To use an alternate location,
# either edit this line or set MPICH_PREFIX in your environment.
# see select_mpi for the set of default MPI selections
# default to MPI used for build
MPICH_PREFIX=${MPICH_PREFIX:-`cat .prefix 2>/dev/null`}

trap "exit 1" SIGHUP SIGTERM SIGINT

BASE_DIR="osu-micro-benchmarks-5.9/mpi/"

if [ -z "$1" -o x"$1" == x"-h" -o x"$1" == x"--help" ]
then 
	echo "Usage: $0 <number_of_processes> <command> [options]"
	echo "    number_processes may be 'all' in which case one rank will be started for"
	echo "                     every process in the mpi_hosts file."
	echo "    <command> osu benchmark to run"
	echo "    [options] are passed to <command>"
	echo "For example: $0 2 osu_allgatherv -f"
	echo
	echo -n "Possible commands are: "
	sep=""
	for f in $(find ${BASE_DIR} -executable -type f); do
		echo -n $sep$(basename $f)
		sep=", "
	done
	echo
	echo
	echo "To get more details about [options] available: $0 2 <command> -h"
	echo "For example: $0 2 osu_fop_latency -h"
	exit 1
fi

NUM_PROCESSES=$1
shift

if [ $# -lt 1 ]; then
	echo "You must specify an OSU benchmark."
	exit 1
fi

CMD=`find ${BASE_DIR} -name "$1"`
if [ -z ${CMD} ]; then
	echo "$1 is not a valid OSU benchmark."
	exit 1
fi

APP="$1"
shift
LOGFILE=
. ./prepare_run


(
	echo " Running $CMD ..."
	show_mpi_hosts
	set -x
	$MPI_RUN_CMD $CMD "$@"
	set +x
) 2>&1 | tee -i -a $LOGFILE
echo "########################################### " >> $LOGFILE
